### ISSUE TITLE
Weird UI quirk when installed from ArgoCD

### ISSUE THREAD

**Issue by dudash** [kiali/openshift-servicemesh-plugin#147]
I installed the ossmconsole using ArgoCD and it is acting differently than normal. 
1) It shows a login button instead of being authenticated, when I click the login button it just errors out.
2) If I goto full Kiali and login, and then come back to the OpenShift console I see UIs but they are full Kiali and not the embeded views.

Here are some screenshots of the weird behavior:
<img width="1728" alt="Screenshot 2023-05-01 at 10 05 04 PM" src="https://user-images.githubusercontent.com/116840/235564182-9f0edab9-19b3-40de-a48b-90f603e02349.png">

<img width="764" alt="Screenshot 2023-05-01 at 10 05 07 PM" src="https://user-images.githubusercontent.com/116840/235564209-ff8334b0-f55a-4bd8-aa86-784193a260c8.png">

<img width="1728" alt="Screenshot 2023-05-01 at 9 48 48 PM" src="https://user-images.githubusercontent.com/116840/235564023-4199edde-02f1-4ce6-acbb-420e6ef46b5b.png">

Here is my ArgoCD config and a link to my repo if you want to test:
https://github.com/dudash/istio-managed-openshift-demo/tree/main/system/service-mesh
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: ossmconsole-operator
  namespace: openshift-operators
spec:
  channel: candidate
  installPlanApproval: Automatic
  name: ossmconsole
  source: community-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: ossmconsole-operator.v0.3.0
```

```
apiVersion: kiali.io/v1alpha1
kind: OSSMConsole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  namespace: openshift-operators
  name: ossmconsole
```
