### ISSUE TITLE
Installing OSSMC plugin fails on IPv6 cluster

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#281]
### Describe the bug

When I installed OSSMC plugin on the OCP IPv6 cluster,

```
oc create -f - <<EOF
apiVersion: kiali.io/v1alpha1
kind: OSSMConsole
metadata:
  namespace: openshift-operators
  name: ossmconsole
EOF
```

the ossmconsole plugin is not able to be loaded.

![image](https://github.com/kiali/openshift-servicemesh-plugin/assets/122779323/fa3f97b8-e3ac-4bc2-b693-e32eba406a3e)

After some time, it shows it as failed

![image](https://github.com/kiali/openshift-servicemesh-plugin/assets/122779323/317f37f4-2a81-4b43-a416-65c4f5e748d5)

status:

![image](https://github.com/kiali/openshift-servicemesh-plugin/assets/122779323/f2712099-2a18-477f-acdf-f323bfc5e530)

`ossmconsole` pod in openshift-operators doesn't contain any error.

### Expected Behavior

OSSMC is installed successfully on IPv6 cluster

### What are the steps to reproduce this bug?

1. Install OSSMC plugin on IPv6 cluster

### Environment

- **OSSMC/Kiali version:** 1.73
- **OpenShift version:** 4.14
- **OSSM version:** 2.5
