### ISSUE TITLE
plugin location hardcoded to ossmconsole

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/openshift-servicemesh-plugin#87]
The plugin location is hardcoded to be expected to be `ossmconsole`. That is wrong. We need to fix this:

https://github.com/kiali/openshift-servicemesh-plugin/blob/v0.1.0/operator/roles/default/ossmconsole-deploy/templates/openshift/consoleplugin.yaml#L10

**Comment by jmazzitelli** [comment]
I do not see this in my own dev build. So something is breaking the plugin either in the CI workflow build OR in the way it is deployed via OLM (perhaps some security permissions thing? I did notice the Install Guide ends up installing the plugin pod in the openshift-operators ns and the dev makefile put it in ossmconsole - perhaps something is up with the way internal ns are treated?)

**Comment by jmazzitelli** [comment]
```
$ oc logs -n istio-system -l app=ossmconsole
OpenShift Service Mesh Console: Version=[], Commit=[]
```

Not due to the namespace - even in istio-system it doesn't work.

Looks like the build is bad.

**Comment by jmazzitelli** [comment]
I even switched to using the images I pushed to the internal registry (that I know worked) and I still can't get the plugin to work:

```
$ oc get pods -l app=ossmconsole -n istio-system -o jsonpath={.items[0].spec.containers[0].image} ; echo
image-registry.openshift-image-registry.svc:5000/kiali/ossmconsole:dev

$ oc get pods -l app=ossmconsole-operator -n openshift-operators -o jsonpath={.items[0].spec.containers[0].image} ; echo
image-registry.openshift-image-registry.svc:5000/kiali/ossmconsole-operator:dev
```

This images work when I deploy using the make targets (which create a OLM catalog, so it isn't like we are completely different - its still OLM).

There might be some differences in the metadata that causes the problem.

**Comment by jmazzitelli** [comment]
This is how I tested the dev images but installing via community OLM (I need to point to the internal image registry):

```
OPERATOR_NAMESPACE="openshift-operators"
ENV_NAME="ALLOW_AD_HOC_OSSMCONSOLE_IMAGE"
ENV_VALUE="true"
oc -n ${OPERATOR_NAMESPACE} patch $(oc -n ${OPERATOR_NAMESPACE} get csv -o name | grep ossmconsole) --type=json -p "[{'op':'replace','path':"/spec/install/spec/deployments/0/spec/template/spec/containers/0/env/$(oc -n ${OPERATOR_NAMESPACE} get $(oc -n ${OPERATOR_NAMESPACE} get csv -o name | grep ossmconsole) -o jsonpath='{.spec.install.spec.deployments[0].spec.template.spec.containers[0].env[*].name}' | tr ' ' '\n' | cat --number | grep ${ENV_NAME}
```

```
oc -n openshift-operators patch $(oc -n openshift-operators get csv -o name | grep ossmconsole) --type=json -p "[{'op':'replace','path':'/spec/install/spec/deployments/0/spec/template/spec/containers/0/image','value':'image-registry.openshift-image-registry.svc:5000/kiali/ossmconsole-operator:dev'}]"
```

Then create the CR:

```
apiVersion: kiali.io/v1alpha1
kind: OSSMConsole
metadata:
  name: ossmconsole
  namespace: istio-system
spec:
  deployment:
    imageName: image-registry.openshift-image-registry.svc:5000/kiali/ossmconsole
    imagePullPolicy: Always
    imageVersion: dev
  kiali:
    serviceName: ""
    serviceNamespace: ""
    servicePort: 0
    url: ""
```
